name: listenable_builder
description: A wrapper around AnimatedBuilder so that it may be called ListenableBuilder
version: 1.0.0
author: Kevin Gray
homepage: TBD

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
